#!/bin/sh

status() {
[ $(cat /sys/class/net/w*/operstate) = down ] && echo false && exit
echo true
}

name() {
    nmcli | grep "^wlp" | sed 's/\ connected\ to\ /Connected to /g' | cut -d ':' -f2
}

[ "$1" = "status" ] && status && exit
[ "$1" = "name" ] && name && exit
