#!/bin/sh

status() {
[ $(cat /sys/class/net/w*/operstate) = down ] && echo  && exit
echo 
}

name() {
nmcli | grep "^wlp" | sed 's/\ connected\ to\ //g' | cut -d ':' -f2
}

[ "$1" = "status" ] && status && exit
[ "$1" = "name" ] && name && exit
