[[repos]]
url = "https://raw.githubusercontent.com/leftwm/leftwm-community-themes/master/known.toml"
name = "community"
definitions_version = 1
themes = []

[[repos]]
url = "localhost"
name = "LOCAL"
definitions_version = 1

[[repos.themes]]
name = "default"
directory = "/home/elal/.config/leftwm/themes/default"
version = "0.0.0"
leftwm_versions = "*"
current = false

[[repos.themes]]
name = "gruv"
directory = "/home/elal/.config/leftwm/themes/gruv"
version = "0.0.0"
leftwm_versions = "*"
current = true
